project:
  type: website
  output-dir: docs

website:
  title: "Ryder Shoots 📸"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Posts
        menu: 
          - href: foggyapps.qmd
          - href: latewinter.qmd
      - archive.qmd
    right: 
      - contact.qmd
  
          
format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true



